### ISSUE TITLE
Feature Request: One badge that averages all four scores

### ISSUE THREAD

**Issue by rootulp** [emazzotta/lighthouse-badges#1]
For [rootulp.com](https://github.com/rootulp/rootulp.com) I'd like to use a cumulative lighthouse score with a shorter lowercase subject (perhaps just `lighthouse`). So something like this [badge](https://img.shields.io/badge/lighthouse-94%25-green.svg)

**Comment by emazzotta** [comment]
Thanks, good suggestion, I'm working on it 👍

**Comment by emazzotta** [comment]
@rootulp done, just add the `-s` parameter :)
