### ISSUE TITLE
How to pass options do the lighthouse itself?

### ISSUE THREAD

**Issue by AdrianoCahete** [emazzotta/lighthouse-badges#27]
Today, lighthouse-badges test on top of the default mobile options. In lighthouse cli you can pass the `--emulated-form-factor desktop` to test against desktop UA.  
How I can do this with badges?

**Comment by emazzotta** [comment]
Hi @AdrianoCahete 

Thanks for raising the issue, I just added the functionality to pass custom lighthouse parameters.
Simply create an environment variable like so:

```
export LIGHTHOUSE_BADGES_PARAMS="--emulated-form-factor=desktop"
```

This will be passed to the lighthouse process directly.

**Comment by AdrianoCahete** [comment]
Tested with `"cross-env LIGHTHOUSE_BADGES_PARAMS=\"--emulated-form-factor=desktop\" npx lighthouse-badges --urls <my-url-here> -r -o ./static/performance/"` and didn't work. 

What I'm doing wrong?

**Comment by emazzotta** [comment]
I ran this command in the terminal:

```
cross-env LIGHTHOUSE_BADGES_PARAMS="--emulated-form-factor=desktop" npx lighthouse-badges --urls https://emanuelemazzotta.com -r -o ./static/performance/
```

It works just fine. Could you elaborate what you mean by "didn't work"? What error message or issue are you experiencing?

**Comment by emazzotta** [comment]
Hi @AdrianoCahete 

Given the inactivity I assume you managed to solve the issue. I'll close this ticket in ~3 days.

**Comment by AdrianoCahete** [comment]
I didn't have time to see this again, but I think that the problem is really in my end.

**Comment by stepanjakl** [comment]
Hi, just to let you know that the emulation configuration [changed](https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md). The flag is now called `--emulated-preset=desktop`.

**Comment by emazzotta** [comment]
Thanks for the hint!

Since the parameter is directly passed to the lighthouse process, there is no need for any changes to the code from my side.

This will work:
```
cross-env LIGHTHOUSE_BADGES_PARAMS="--emulated-preset=desktop" npx lighthouse-badges --urls <my-url-here> -r -o ./static/performance/
```

I updated the [README](https://github.com/emazzotta/lighthouse-badges/commit/ad8b480da48401c7b44805d515564049d5fe5e7a) accordingly, however 👍.

**Comment by stepanjakl** [comment]
Hey, so `--emulated-preset=desktop` is not actually working, it still emulates a mobile device.

You have to put through `--preset=desktop`.

My apologies

**Comment by emazzotta** [comment]
You're right, thanks for the hint 👍
