### ISSUE TITLE
Save artifacts?

### ISSUE THREAD

**Issue by tsirlucas** [emazzotta/lighthouse-badges#3]
Hey @emazzotta, love what you're doing with **lighthouse-badges**.

So, I have a project with **Travis** and **gh-pages** and I'm using the following steps:

1 - Build the project

2 - Publish the files with **gh-pages**

3 - Run **lighthouse-badges** on the production URLs

4 - Publish the **SVGs** with **gh-pages**

And I'm using the published **SVGs** URLs on the **README**, this way I always have **the latest build results** on the screen.

The thing is: I want to be able to, somehow, show the **lighthouse report** that gave me that score, and the **--save-artifacts** flag can provide the **HTML report file**.

I could simply do **another lighthouse test** to get the **HTML report file**, but lighthouse's results **may be different**, you know?

**What about add a --save-artifacts flag to lighthouse-badges too?** 

Or simply use the **--save-artifacts** when running lighthouse

**Comment by emazzotta** [comment]
Good idea, I'll work on this 👍

**Comment by emazzotta** [comment]
This is implemented. I named the flag *--save-report* since I'm not saving the log file, just the html report.

**Comment by tsirlucas** [comment]
Love u
