### ISSUE TITLE
Support for localhost?

### ISSUE THREAD

**Issue by spmcbride1201** [emazzotta/lighthouse-badges#4]
My web app is pretty locked down in production. I'd like to be able to add an npm script to generate these badges while running my app locally via webpack-dev-server. However, I currently crash with `Error: stdout maxBuffer exceeded` when running locally against my locally served app.

I'm able to hit public youtube like your example without error, so I'm curious if this is a known limitation or if I might be able to set a configuration to increate the maxBuffer.

Thanks!

```bash
lighthouse-badges --urls http://localhost:3000/
Lighthouse performance test running... (this might take a while)
(node:19025) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: stdout maxBuffer exceeded
(node:19025) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by emazzotta** [comment]
Hi @spmcbride1201 

Thanks for the issue, I assume the output was simply too big and the maxBuffer thus got exceeded. Running this on localhost should normally work just fine. I increased the maxBuffer now, can you try again?
