### ISSUE TITLE
Pass cookie to lighthouse (--extra-headers)

### ISSUE THREAD

**Issue by edxz101** [emazzotta/lighthouse-badges#401]
Hello, first of all thanks for the work @emazzotta . I wanted to ask how to pass a cookie to lighthouse. For example with the --extra-headers option
Thank you!

**Comment by emazzotta** [comment]
Hi @edxz101 

You can pass parameters to the lighthouse process directly via environment variable as described in the [README](https://github.com/emazzotta/lighthouse-badges/blob/master/README.md) (via `LIGHTHOUSE_BADGES_PARAMS` variable). 

Have you tried that already?

**Comment by edxz101** [comment]
TRUE! I ran it in the following way in Docker and it worked perfectly.

`export MY_TOKEN="xxxxxxxxxxxxxxx"`
`docker run --rm -v $PWD/test_results:/home/chrome/reports -e LIGHTHOUSE_BADGES_PARAMS='--extra-headers "{\"Cookie\":\"MyCustomCookie='${MY_TOKEN}'\"}"' emazzotta/lighthouse-badges /bin/sh -c "lighthouse-badges --urls https://mycustomdomain.com -r"`

thx @emazzotta

**Comment by emazzotta** [comment]
Great, thank you for sharing!
