### ISSUE TITLE
Error when running for more than one url

### ISSUE THREAD

**Issue by DaveChamberlinKidd** [emazzotta/lighthouse-badges#455]
## Failure scenario

1. Copy `npx` command from readme - `npx lighthouse-badges --urls https://www.youtube.com/ https://www.youtube.com/feed/trending -o test_results`
2. Run it

### Expected Behaviour

Lighthouse reports should be run and the badges created

### Actual Behaviour
```
10:20 $ npx lighthouse-badges --urls https://www.youtube.com/ https://www.youtube.com/feed/trending -o test_results
  ◡ Running Lighthouse, please wait...SyntaxError: The "start lh:runner:gather" performance mark has not been set
```

## Success scenario (with only one url)

1. Modify `npx` command from readme to remove second url - `npx lighthouse-badges --urls https://www.youtube.com/ -o test_results`
2. Run it

### Expected Behaviour

Lighthouse reports should be run and the badges created

### Actual Behaviour

Lighthouse reports run and the badges created

## Environment Information

- **Operating System**: Linux Ubuntu 5.14.0-1052-oem
- **Lighthouse-Badges Version:** 1.2.8
- **Node Version:** 18.16.0, 16.20.0

## Additional Information 

It appears this may be due to running lighthouse in parallel see [lighthouse issue](https://github.com/GoogleChrome/lighthouse/issues/7187) but I haven't investigated further.

(Please tick where applicable)
- [/] The issue persists with the npm version

**Comment by emazzotta** [comment]
Thanks for the hint @DaveChamberlinKidd, I've updated the readme accordingly, that only one url is supported (for the time being).
